version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - aliceblue
  - ANSIREGEX
  - antiquewhite
  - astro
  - bithound
  - blanchedalmond
  - blueviolet
  - buildable
  - burlywood
  - cadetblue
  - caseta
  - cbar
  - Chrono
  - codeowners
  - codez
  - cornflowerblue
  - cornsilk
  - creationrc
  - darkcyan
  - darkgoldenrod
  - darkgray
  - darkgreen
  - darkgrey
  - darkkhaki
  - darkmagenta
  - darkolivegreen
  - darkorange
  - darkorchid
  - airballoon
  - allo
  - angellist
  - angularjs
  - aosc
  - appcelerator
  - appstore
  - aptana
  - archlinux
  - areaspline
  - audiobook
  - autorenew
  - backburger
  - bandcamp
  - behance
  - bintray
  - bouy
  - bugsense
  - buysellads
  - candycane
  - carot
  - cicling
  - clippy
  - clouddrive
  - codeigniter
  - codepen
  - codiepie
  - codrops
  - coffe
  - connectdevelop
  - contao
  - creativecommons
  - crosshairs
  - cssdeck
  - dashcube
  - deskphone
  - deviantart
  - devuan
  - dialpad
  - digg
  - disqus
  - dlang
  - douban
  - dreamweaver
  - dribbble
  - eercast
  - ello
  - emby
  - envato
  - envira
  - eventbrite
  - evernote
  - expeditedssl
  - extjs
  - feedly
  - flickr
  - fonticons
  - forumbee
  - forwardslash
  - freecodecamp
  - futbol
  - galery
  - gantt
  - giftcard
  - gittip
  - glassdoor
  - gopro
  - gratipay
  - grav
  - hackernews
  - handsdown
  - handsup
  - harddisk
  - hexbin
  - hololens
  - houzz
  - hspa
  - hubot
  - imdb
  - instapaper
  - ioxhost
  - jeepney
  - joomla
  - jsfiddle
  - kickstarter
  - kodi
  - komodo
  - krakenjs
  - laravel
  - lastpass
  - leanpub
  - linuxmint
  - lumx
  - mageia
  - magento
  - mailchimp
  - materializecss
  - maxcdn
  - meanpath
  - medkit
  - meteorfull
  - mitlicence
  - mixcloud
  - mobileme
  - modernizr
  - modx
  - msdos
  - msql
  - navicon
  - netbeans
  - netmagazine
  - nixos
  - octagram
  - octoface
  - odnoklassniki
  - onedrive
  - onenote
  - opencart
  - opensource
  - optin
  - pagelines
  - paintcan
  - partlycloudy
  - photoshop
  - pilcrow
  - pinterest
  - pokeball
  - pomodoro
  - qqchat
  - qrcode
  - quadcopter
  - quicktime
  - quora
  - rasberry
  - raspberrypi
  - ravelry
  - reblog
  - renren
  - roomba
  - scatterplot
  - scribd
  - scriptcs
  - sellsy
  - senchatouch
  - shirtsinbulk
  - simplybuilt
  - sizzlejs
  - skyatlas
  - slideshare
  - soundcloud
  - sqllite
  - stackexchange
  - stackoverflow
  - stange
  - stumbleupon
  - svideo
  - symfony
  - teamviewer
  - techcrunch
  - textdirection
  - themeisle
  - thumbsdown
  - thumbsup
  - timelapse
  - trackpad
  - tshirt
  - umbraco
  - unfill
  - ungroup
  - untappd
  - vcard
  - venmo
  - viacoin
  - viadeo
  - vuejs
  - webplatform
  - wechat
  - weibo
  - weixin
  - wiiu
  - wpbeginner
  - wpexplorer
  - wpforms
  - wunderlist
  - xmpp
  - yoast

  - darkred
  - darksalmon
  - darkseagreen
  - darkslateblue
  - darkslategray
  - darkslategrey
  - darkturquoise
  - darkviolet
  - datetime
  - dbaeumer
  - deeppink
  - deepskyblue
  - devkit
  - dhall
  - dimgray
  - dimgrey
  - dodgerblue
  - entites
  - esbenp
  - execa
  - exiasr
  - falsey
  - fastify
  - floralwhite
  - fontawesome
  - forestgreen
  - fuzzysort
  - gainsboro
  - gbit
  - ghostwhite
  - gotify
  - greenyellow
  - gridsome
  - hadolint
  - hass
  - hassio
  - hmss
  - homeassistant
  - hotpink
  - idris
  - indianred
  - intellij
  - interwebs
  - julianday
  - kbit
  - keyfile
  - keylist
  - keymap
  - Keymaps
  - keypresses
  - kusto
  - lavenderblush
  - lawngreen
  - lemonchiffon
  - lifecycles
  - lightcoral
  - lightcyan
  - lightgoldenrodyellow
  - lightgray
  - lightgreen
  - lightpink
  - lightsalmon
  - lightseagreen
  - lightskyblue
  - lightslategray
  - lightslategrey
  - lightsteelblue
  - lightyellow
  - limegreen
  - lutron
  - managerrc
  - maxage
  - mbar
  - mbit
  - mediumaquamarine
  - mediumblue
  - mediumorchid
  - mediumpurple
  - mediumseagreen
  - mediumslateblue
  - mediumspringgreen
  - mediumturquoise
  - mediumvioletred
  - midnightblue
  - milli
  - mintcream
  - mireds
  - mistyrose
  - mrad
  - navajowhite
  - navyblue
  - nocheck
  - npmjs
  - nrwl
  - nsoult
  - numlen
  - nxignore
  - oldlace
  - olivedrab
  - orangered
  - pagedown
  - pageup
  - pagga
  - palegoldenrod
  - palegreen
  - paleturquoise
  - palevioletred
  - papayawhip
  - peachpuff
  - pico
  - pino
  - pkief
  - postdata
  - powderblue
  - prettyrc
  - proto
  - purescript
  - reftimes
  - rgbw
  - rgbww
  - rosybrown
  - royalblue
  - rrule
  - saddlebrown
  - sandybrown
  - seagreen
  - searchbox
  - shellcheck
  - sinm
  - sinonjs
  - skyblue
  - slateblue
  - slategray
  - slategrey
  - snapse
  - sonarjs
  - springgreen
  - steelblue
  - terminalizer
  - testrc
  - timonwong
  - toolbelt
  - tput
  - tsdoc
  - typeof
  - undici
  - unitless
  - unpublish
  - UNSORTABLE
  - visbility
  - vsix
  - whitesmoke
  - womp
  - writerrc
  - yellowgreen
  - zipignore
ignoreWords: []
import: []
